### ISSUE TITLE
[Feature]: Support PaddingMode NONE in 3D

### ISSUE THREAD

**Issue by vasl12** [BioMedIA/deepali#87] opened 2023-07-18 14:38 UTC
The dimensions of a 3D image change after Affine registration. Is this related to padding and if yes how can we fix it?

**Comment by aschuh-hf** [comment] 2023-07-18 22:42
Hi Vasilis, could you elaborate on how you apply the affine transformation in order to resample your moving source image?

The `PaddingMode` only relates to how the finite input source image tensor is implicitly padded when sampling at locations outside the source image domain. It does not impact the sampling grid of the warped output image. The sampling grid of the spatially transformed image is usually determined by the sampling grid of the fixed target image, or the `SpatialTransform.grid()` respectively as specified during initialization of the spatial transform.

In case of the `ImageTransformer` (and equally `deepali.modules.SampleImage`) this is the `target` argument of the spatial transformer init function.

https://github.com/BioMedIA/deepali/blob/c47ac8cf81ce0978b3095d79592fcd1f017e23c6/src/deepali/spatial/transformer.py#L127

**Comment by aschuh-hf** [comment] 2023-07-19 09:32
That's odd indeed. What is the code you use to apply the spatial transform?

**Comment by vasl12** [comment] 2023-07-19 09:35
Here is the piece of code for the affine multi-resolution registration and the warping:

```
source = tranformed_images[0]['wat'][tio.DATA]
target = ts['wat'][tio.DATA]

transform_affine = multi_resolution_registration(
    target=target,
    source=source,
    transform=spatial.FullAffineTransform,
    optimizer=(optim.Adam, {"lr": 1e-3}),
    loss_fn=lambda a, b, _: sim_loss(a, b),
    device=device,
    levels=3,
    iterations=1000
)
transform_affine = transform_affine.cpu()
source = tranformed_images[0]['wat'][tio.DATA]
target = ts['wat'][tio.DATA]

transform_affine = multi_resolution_registration(
    target=target,
    source=source,
    transform=spatial.FullAffineTransform,
    optimizer=(optim.Adam, {"lr": 1e-3}),
    loss_fn=lambda a, b, _: sim_loss(a, b),
    device=device,
    levels=3,
    iterations=1000
)
transform_affine = transform_affine.cpu()
```

**Comment by aschuh-hf** [comment] 2023-07-19 10:49
I see. The change in image size is probably caused by the multi-resolution pyramid. The sizes are adjusted such that doubling the size going from a coarser to the next finer level will eventually yield the closest size at the finest resolution to the given input image size. This is to enable efficient subdivision of a FFD control point grid.

The demo function would probably have to adopted a bit to account for this such that the output has the expected size. This can be done by passing the desired output image grid as `target` to the ImageTransformer used to apply the obtained transform. The `transform.grid()` is not identical to the input `target.grid()` here, but it's the former that's used when the image transformer is created as in `ImageTransformer(transform)`.

Can you try changing the final transformer to `ImageTransformer(transform, target=target.grid())` instead?

**Comment by aschuh-hf** [comment] 2023-07-25 11:39
I've just merged a change which allows the sampling grid of the transformed image (output of `ImageTransformer`) to have a different normalized coordinate domain in world space than the spatial transform itself.

**Closed** 2023-07-25 11:38 UTC
